import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { useState } from 'react'

export async function getStaticProps() {
  const res = await fetch('https://api.github.com/orgs/traefik/repos')
  const repos = await res.json()

  return {
    props: {
      repos,
    },
  }
}

export default function Home({ repos }) {
  const [displayedRepos, setDisplayedRepos] = useState(repos);

  const handleSearch = (e) => {
    const result = repos.filter(repo => {
      return repo.full_name.includes(e.target.value)
    })
    setDisplayedRepos(result)
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Github Indicators Explorer</title>
        <meta name="Github Indicators Explorer" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Github Indicators Explorer
        </h1>

        <p className={styles.description}>
          GitHub Indicators Explorer can help you get key metrics about your favourite github repositories.
        </p>

        <div className={styles.grid}>
          <h2 className={styles.subtitle}>Select a repository</h2>
          <input className={styles.search_bar} placeholder="Search..." onChange={handleSearch} />
          {displayedRepos.map((repo) => (
            <div className={styles.card}>
              <img src={repo.owner.avatar_url} className={styles.avatar} />
              <div className={styles.card_body}>
                <h3>{repo.full_name}</h3>
                <p>{repo.description}</p>
              </div>
              <p className={styles.select_text}>select</p>
            </div>
          ))}
        </div>
      </main>
    </div>
  )
}
